jobs:
  - name: management-dev
    max_in_flight: 1
    plan:
      - get: docker-nginx-s3
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: "default"
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: "default"