resources:
  - name: dwpdigital-nginx-s3
    type: registry-image-resource
    source:
      repository: dwpdigital/nginx-s3
    check_every: 5m

  - name: ecr-dwpdigital-nginx-s3-dev
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "nginx-s3"

  - name: ecr-dwpdigital-nginx-s3
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "nginx-s3"
      aws_role_arn: arn:aws:iam::((aws_account.management)):role/ci

jobs:
  - name: mirror-dwpdigital-nginx-s3-dev
    serial_groups: [nginx-s3]
    plan:
      - get: dwpdigital-nginx-s3
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-nginx-s3-dev
        params:
          image: "dwpdigital-nginx-s3/image.tar"
        attempts: 3

  - name: mirror-dwpdigital-nginx-s3
    serial_groups: [nginx-s3]
    plan:
      - get: dwpdigital-nginx-s3
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-nginx-s3
        params:
          image: "dwpdigital-nginx-s3/image.tar"
        attempts: 3
