jobs:
  - name: docker-nginx-s3-pr
    plan:
      - get: docker-nginx-s3-pr
        trigger: true
        version: every
      - put: docker-nginx-s3-pr
        params:
          path: docker-nginx-s3-pr
          status: pending
        input_mapping:
          docker-nginx-s3: docker-nginx-s3-pr
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          docker-nginx-s3: docker-nginx-s3-pr
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          docker-nginx-s3: docker-nginx-s3-pr
        params:
          TF_WORKSPACE: "default"
          DETAILED_EXITCODE: ""
        on_failure:
          put: docker-nginx-s3-pr
          params:
            path: docker-nginx-s3-pr
            status: failure
        on_success:
          put: docker-nginx-s3-pr
          params:
            path: docker-nginx-s3-pr
            status: success
